//! Golden test suite for Vajra.
//!
//! Compares current analysis output against captured golden files to catch
//! regressions in output format, scoring, rendering, and analysis.
//!
//! Golden files are generated by `cargo run -p vajra-cli --bin generate-corpus`.
//! If the corpus does not exist, tests are skipped with a message.

use std::fs;
use std::path::{Path, PathBuf};

use vajra_anomaly::AnomalyAnalyzer;
use vajra_core::formats::parse_file_auto;
use vajra_drift::full_drift;
use vajra_essence::{EngineerProfile, EssenceBuilder};
use vajra_fingerprint::FingerprintAnalyzer;
use vajra_stats::StatsAnalyzer;
use vajra_types::traits::{Analyzer, ConcernProfile, OutputFormat};
use vajra_types::Document;

/// Root of the corpus directory, relative to the workspace root.
fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join("corpus")
}

fn golden_dir() -> PathBuf {
    corpus_dir().join("golden")
}

fn hex(bytes: &[u8; 32]) -> String {
    use std::fmt::Write;
    bytes.iter().fold(String::with_capacity(64), |mut s, b| {
        let _ = write!(s, "{b:02x}");
        s
    })
}

/// Collect all corpus files (excluding the golden directory).
fn collect_corpus_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    collect_recursive(dir, &mut files);
    files.sort();
    files
}

fn collect_recursive(dir: &Path, files: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    for entry in entries {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };
        let path = entry.path();

        if path.file_name().and_then(|n| n.to_str()) == Some("golden") {
            continue;
        }

        if path.is_dir() {
            collect_recursive(&path, files);
        } else {
            let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
            match ext {
                "json" | "ndjson" | "yaml" | "yml" | "csv" | "md" => {
                    files.push(path);
                }
                _ => {}
            }
        }
    }
}

/// Compute the golden file stem from a corpus file path.
fn golden_stem(file: &Path, corpus_root: &Path) -> String {
    let rel = file.strip_prefix(corpus_root).unwrap_or(file);
    rel.to_string_lossy().replace(['/', '\\'], "__")
}

/// Tolerance for floating-point comparison. This accounts for
/// platform-dependent rounding in f64 arithmetic (e.g. entropy, MAD).
const FLOAT_TOLERANCE: f64 = 1e-10;

/// Compare two JSON values structurally, treating floats as approximately
/// equal within [`FLOAT_TOLERANCE`]. Returns `None` if the values match,
/// or a human-readable diff if they differ.
fn json_diff(golden: &serde_json::Value, actual: &serde_json::Value) -> Option<String> {
    let mut diffs = Vec::new();
    json_diff_recursive(golden, actual, "$", &mut diffs);
    if diffs.is_empty() {
        None
    } else {
        Some(diffs.join("\n"))
    }
}

fn json_diff_recursive(
    golden: &serde_json::Value,
    actual: &serde_json::Value,
    path: &str,
    diffs: &mut Vec<String>,
) {
    use serde_json::Value;

    match (golden, actual) {
        (Value::Null, Value::Null) => {}
        (Value::Bool(a), Value::Bool(b)) if a == b => {}
        (Value::String(a), Value::String(b)) if a == b => {}
        (Value::Number(a), Value::Number(b)) => {
            // Compare numbers with floating-point tolerance
            let af = a.as_f64().unwrap_or(f64::NAN);
            let bf = b.as_f64().unwrap_or(f64::NAN);
            if (af - bf).abs() > FLOAT_TOLERANCE && !(af.is_nan() && bf.is_nan()) {
                diffs.push(format!("  {path}: golden={a}, actual={b}"));
            }
        }
        (Value::Array(a), Value::Array(b)) => {
            if a.len() != b.len() {
                diffs.push(format!(
                    "  {path}: array length golden={}, actual={}",
                    a.len(),
                    b.len()
                ));
                return;
            }
            for (i, (ga, aa)) in a.iter().zip(b.iter()).enumerate() {
                json_diff_recursive(ga, aa, &format!("{path}[{i}]"), diffs);
            }
        }
        (Value::Object(a), Value::Object(b)) => {
            // Check keys present in golden but missing in actual
            for key in a.keys() {
                if !b.contains_key(key) {
                    diffs.push(format!("  {path}.{key}: missing in actual"));
                }
            }
            // Check keys present in actual but missing in golden
            for key in b.keys() {
                if !a.contains_key(key) {
                    diffs.push(format!("  {path}.{key}: unexpected in actual"));
                }
            }
            // Compare shared keys
            for key in a.keys() {
                if let (Some(gv), Some(av)) = (a.get(key), b.get(key)) {
                    json_diff_recursive(gv, av, &format!("{path}.{key}"), diffs);
                }
            }
        }
        _ => {
            // Type mismatch or value mismatch
            diffs.push(format!("  {path}: golden={golden}, actual={actual}"));
        }
    }
}

// ---------------------------------------------------------------------------
// Re-analysis functions (mirror the capture logic in generate_corpus.rs)
// ---------------------------------------------------------------------------

fn analyze_inspect(doc: &Document) -> serde_json::Value {
    let meta = doc.metadata();
    let all_paths = doc.trie().all_paths();
    let mut path_views = Vec::new();

    for wp in &all_paths {
        if let Some(node) = doc.trie().get(wp) {
            let m = &node.metadata;
            path_views.push(serde_json::json!({
                "path": wp.to_string(),
                "dominant_type": m.dominant_type().map_or("unknown".to_string(), |t| t.to_string()),
                "count": m.count,
                "type_instability": m.type_instability(),
                "null_rate": m.null_rate(),
            }));
        }
    }

    let fp = match FingerprintAnalyzer.analyze(doc) {
        Ok(fp) => serde_json::json!({
            "path_set": hex(&fp.path_set),
            "typed_path": hex(&fp.typed_path),
            "shape": hex(&fp.shape),
        }),
        Err(e) => serde_json::json!({"error": format!("{e}")}),
    };

    serde_json::json!({
        "metadata": {
            "total_nodes": meta.total_nodes,
            "max_depth": meta.max_depth,
            "distinct_paths": meta.distinct_paths,
            "raw_size_bytes": meta.raw_size_bytes,
        },
        "paths": path_views,
        "fingerprints": fp,
    })
}

fn analyze_stats(doc: &Document) -> serde_json::Value {
    let result = match StatsAnalyzer.analyze(doc) {
        Ok(r) => r,
        Err(e) => return serde_json::json!({"error": format!("{e}")}),
    };

    let mut paths_json = Vec::new();
    for (wp, stats) in &result.paths {
        let numeric = stats.numeric_stats.as_ref().map(|ns| {
            serde_json::json!({
                "min": ns.min,
                "max": ns.max,
                "mean": ns.mean,
                "median": ns.median,
                "mad": ns.mad,
                "p05": ns.p05,
                "p25": ns.p25,
                "p75": ns.p75,
                "p95": ns.p95,
            })
        });

        let top_values: Vec<serde_json::Value> = stats
            .top_values
            .iter()
            .map(|(v, c)| {
                serde_json::json!({
                    "value": v,
                    "count": c,
                })
            })
            .collect();

        paths_json.push(serde_json::json!({
            "path": wp.to_string(),
            "entropy": stats.entropy,
            "normalized_entropy": stats.normalized_entropy,
            "cardinality": stats.cardinality,
            "total_count": stats.total_count,
            "max_rarity": stats.max_rarity,
            "numeric": numeric,
            "top_values": top_values,
        }));
    }

    serde_json::json!({"paths": paths_json})
}

fn analyze_fingerprint(doc: &Document) -> serde_json::Value {
    let result = match FingerprintAnalyzer.analyze(doc) {
        Ok(r) => r,
        Err(e) => return serde_json::json!({"error": format!("{e}")}),
    };

    let mut motifs: Vec<serde_json::Value> = result
        .subtree_frequencies
        .iter()
        .filter(|(_, &count)| count > 1)
        .map(|(h, &count)| serde_json::json!({"hash": hex(h), "count": count}))
        .collect();
    motifs.sort_by(|a, b| {
        b["count"]
            .as_u64()
            .unwrap_or(0)
            .cmp(&a["count"].as_u64().unwrap_or(0))
    });

    serde_json::json!({
        "path_set": hex(&result.path_set),
        "typed_path": hex(&result.typed_path),
        "shape": hex(&result.shape),
        "repeated_motifs": motifs,
    })
}

fn analyze_anomalies(doc: &Document) -> serde_json::Value {
    let analyzer = AnomalyAnalyzer::default();
    let report = match analyzer.analyze(doc) {
        Ok(r) => r,
        Err(e) => return serde_json::json!({"error": format!("{e}")}),
    };

    let instabilities: Vec<serde_json::Value> = report
        .type_instabilities
        .iter()
        .map(|ti| {
            serde_json::json!({
                "path": ti.path,
                "instability": ti.instability,
                "dominant_type": ti.dominant_type,
                "type_distribution": ti.type_distribution,
            })
        })
        .collect();

    let outliers: Vec<serde_json::Value> = report
        .numeric_outliers
        .iter()
        .map(|no| {
            serde_json::json!({
                "path": no.path,
                "value": no.value,
                "z_mad": no.z_mad,
                "median": no.median,
                "mad": no.mad,
            })
        })
        .collect();

    let rare: Vec<serde_json::Value> = report
        .rare_values
        .iter()
        .map(|rv| {
            serde_json::json!({
                "path": rv.path,
                "value": rv.value,
                "count": rv.count,
                "rarity_bits": rv.rarity_bits,
            })
        })
        .collect();

    serde_json::json!({
        "type_instabilities": instabilities,
        "numeric_outliers": outliers,
        "rare_values": rare,
    })
}

fn analyze_essence(doc: &Document) -> serde_json::Value {
    let profile = EngineerProfile;

    let stats = match StatsAnalyzer.analyze(doc) {
        Ok(r) => r,
        Err(_) => return serde_json::json!({"error": "stats analysis failed"}),
    };

    let anomalies = AnomalyAnalyzer::default().analyze(doc).ok();
    let fingerprint = FingerprintAnalyzer.analyze(doc).ok();

    let mut builder = EssenceBuilder::new(doc, &profile).with_stats(&stats);

    if let Some(ref a) = anomalies {
        builder = builder.with_anomalies(a);
    }
    if let Some(ref f) = fingerprint {
        builder = builder.with_fingerprint(f);
    }

    let essence = builder.build();

    match profile.render(&essence, OutputFormat::Json) {
        Ok(rendered) => serde_json::from_str(&rendered)
            .unwrap_or_else(|_| serde_json::json!({"rendered": rendered})),
        Err(e) => serde_json::json!({"error": format!("{e}")}),
    }
}

// ---------------------------------------------------------------------------
// Test runner
// ---------------------------------------------------------------------------

#[test]
fn golden_inspect() -> Result<(), Box<dyn std::error::Error>> {
    run_golden_suite("inspect", analyze_inspect)
}

#[test]
fn golden_stats() -> Result<(), Box<dyn std::error::Error>> {
    run_golden_suite("stats", analyze_stats)
}

#[test]
fn golden_fingerprint() -> Result<(), Box<dyn std::error::Error>> {
    run_golden_suite("fingerprint", analyze_fingerprint)
}

#[test]
fn golden_anomalies() -> Result<(), Box<dyn std::error::Error>> {
    run_golden_suite("anomalies", analyze_anomalies)
}

#[test]
fn golden_essence() -> Result<(), Box<dyn std::error::Error>> {
    run_golden_suite("essence", analyze_essence)
}

#[test]
fn golden_drift() -> Result<(), Box<dyn std::error::Error>> {
    let corpus = corpus_dir();
    let golden = golden_dir();

    if !corpus.exists() || !golden.exists() {
        eprintln!("Corpus not generated. Run: cargo run -p vajra-cli --bin generate-corpus");
        return Ok(());
    }

    let golden_path = golden.join("drift.golden.json");
    if !golden_path.exists() {
        eprintln!("Drift golden file not found, skipping");
        return Ok(());
    }

    let v1_path = corpus.join("api").join("schema_drift.json");
    let v2_path = corpus.join("api").join("schema_drift_v2.json");

    let v1_docs = parse_file_auto(&v1_path, None)?;
    let v2_docs = parse_file_auto(&v2_path, None)?;

    let report = full_drift(&v1_docs[0], &v2_docs[0]);

    let actual = serde_json::json!({
        "structural_similarity": report.structural_similarity,
        "severity": format!("{:?}", report.severity),
        "added_paths": report.path_diff.added.iter().map(|p| p.to_string()).collect::<Vec<_>>(),
        "removed_paths": report.path_diff.removed.iter().map(|p| p.to_string()).collect::<Vec<_>>(),
        "type_changes": report.type_changes.iter().map(|tc| serde_json::json!({
            "path": tc.path,
            "from": tc.from,
            "to": tc.to,
        })).collect::<Vec<_>>(),
        "distributional_drifts": report.distributional_drifts.iter().map(|dd| serde_json::json!({
            "path": dd.path,
            "metric": format!("{:?}", dd.metric),
            "value": dd.value,
        })).collect::<Vec<_>>(),
    });

    let golden_content = fs::read_to_string(&golden_path)?;
    let golden_value: serde_json::Value = serde_json::from_str(&golden_content)?;

    if let Some(diff) = json_diff(&golden_value, &actual) {
        return Err(format!(
            "Drift golden test FAILED\n  golden: {}\n\n{}",
            golden_path.display(),
            diff
        )
        .into());
    }
    Ok(())
}

fn run_golden_suite(
    analysis_name: &str,
    analyzer: fn(&Document) -> serde_json::Value,
) -> Result<(), Box<dyn std::error::Error>> {
    let corpus = corpus_dir();
    let golden = golden_dir();

    if !corpus.exists() || !golden.exists() {
        eprintln!("Corpus not generated. Run: cargo run -p vajra-cli --bin generate-corpus");
        return Ok(());
    }

    let files = collect_corpus_files(&corpus);
    let mut tested = 0u32;
    let mut failed = 0u32;
    let mut failures = Vec::new();

    for file in &files {
        let stem = golden_stem(file, &corpus);
        let golden_path = golden.join(format!("{stem}.{analysis_name}.golden.json"));

        if !golden_path.exists() {
            // Check if there's an error golden
            let error_path = golden.join(format!("{stem}.error.golden.json"));
            if error_path.exists() {
                // File was expected to fail, skip
                continue;
            }
            continue;
        }

        // Parse corpus file
        let docs = match parse_file_auto(file, None) {
            Ok(d) if !d.is_empty() => d,
            _ => continue,
        };

        let actual = analyzer(&docs[0]);

        let golden_content = match fs::read_to_string(&golden_path) {
            Ok(c) => c,
            Err(_) => continue,
        };
        let golden_value: serde_json::Value = match serde_json::from_str(&golden_content) {
            Ok(v) => v,
            Err(_) => continue,
        };

        tested += 1;

        if let Some(diff) = json_diff(&golden_value, &actual) {
            failed += 1;
            failures.push(format!(
                "  FAIL: {} ({})\n{}",
                file.display(),
                analysis_name,
                diff
            ));
        }
    }

    if failed > 0 {
        let report = failures.join("\n");
        return Err(format!(
            "Golden {} tests: {tested} tested, {failed} FAILED\n\n{report}",
            analysis_name
        )
        .into());
    }

    eprintln!(
        "Golden {} tests: {tested} tested, all passed",
        analysis_name
    );
    Ok(())
}
