[package]
name = "vajra-domain-source"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
vajra-types = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
