[package]
name = "vajra-fingerprint"
version.workspace = true
edition.workspace = true

[dependencies]
vajra-types = { workspace = true }
vajra-core = { workspace = true }
blake3 = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }
vajra-core = { workspace = true }
vajra-types = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "fingerprint"
harness = false
